<?
$PERM["/"]["5"]="D";
$PERM["/"]["*"]="R";
$PERM["comps"]["5"]="R";
$PERM[".submainright.menu.php"]["5"]="W";
$PERM[".submainleft.menu.php"]["5"]="W";
$PERM[".submaincenter.menu.php"]["5"]="W";
$PERM[".main.menu.php"]["5"]="W";
$PERM[".bottom.menu.php"]["5"]="W";
$PERM["include"]["5"]="W";
$PERM["download"]["5"]="W";
$PERM["search"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["about"]["5"]="W";
$PERM["index.php"]["5"]="W";
?>